---
title: "project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown for student1
## python for functionA
```{python}

import numpy as np
import time
import matplotlib.pyplot as plt

N = 10
    
m = np.random.normal(size = (N,N))
n = np.random.normal(size = (N,N))
g = np.random.normal(size = (N,1))

def A_i(x):
    m = np.random.normal(size = (N,N))
    n = np.random.normal(size = (N,N))
    g = np.random.normal(size = (N,1))
    res = np.zeros((N,1))
    for i in range(N):
        for j in range(N):
            res[i] += m[i][j]*x[j]
    for i in range(N):
        for j in range(N):
            res[i] += n[i][j]*x[j]
    res = np.add(res, g)
    return res
print(A_i(np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])))

def A_ii(x):

    m = np.random.normal(size = (N,N))
    n = np.random.normal(size = (N,N))
    g = np.random.normal(size = (N,1))

    res = np.zeros((N,1))
    res = np.add(res, np.matmul(m, x))
    res = np.add(res, np.matmul(n, x))
    res = np.add(res, g)
    return res
print(A_ii(np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])))




print(time.time())
def A_iii():
    start = time.time()
    res = []
    for i in range(10000):
        A_i(np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]]))
        res.append(time.time()-start)
    
    
    print(res)
    plt.plot(res)
    plt.show()
    

A_iii()

def A_iiii():
    start = time.time()
    res = []
    for i in range(10000):
        A_ii(np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]]))
        res.append(time.time()-start)
    plt.plot([i for i in range(1,10001)], res)
    plt.show()

A_iiii()
```


## R for functionB
```{r}
x<-c(1:10)
functionB1<-function(x,n){
  input1<-rep(0,times=n)
  input2<-rep(0,times=n)
  output<-rep(0,times=n)
  G<-rep(0,times=n)
  M<-rep(0,times=n*n)
  M3<-rep(0,times=n*n)
  for (i in 1:n){
    G[i]<-rnorm(1)
    for(j in 1:n){
      M[i*n+j]<-rnorm(1)
      M3[i*n+j]<-M[i*n+j]*M[i*n+j]*M[i*n+j]
      input1[i]<-input1[i]+M3[i*n+j]*x[j]
    }
    input2[i]<-G[i]*3
  }
  output<-input1+input2
  return(output)
}
x<-c(1:10)
functionB1(x,10)

```

```{r}
functionB2<-function(x,n){
  M<-matrix(rnorm(n*n),nrow=n,ncol=n)
  G<-matrix(rnorm(n),nrow=n,ncol=1)
  output<-crossprod(M*M*M,x)+G*3
  return(output)
}
x<-c(1:10)
functionB2(x,10)

```


```{r}
functionB1time<-function(){
  start_time<-Sys.time()
  for(i in 1:10000){
    x<-c(1:10)
    functionB1(x,10)
    end_time<-Sys.time()
    t[i]<-end_time-start_time
  }
  plot(1:10000,t,main="Plot",
       xlab="n", ylab="t")
}
functionB1time()


```

```{r}
functionB2time<-function(){
  start_time<-Sys.time()
  for(i in 1:10000){
    x<-c(1:10)
    functionB2(x,10)
    end_time<-Sys.time()
    t[i]<-end_time-start_time
  }
  plot(1:10000,t,main="Plot",
       xlab="n", ylab="t")
}
functionB2time()

```


## student2 function A
=======
## R Markdown for student2

```{r}
A1<-function(x,n){
  ans1<-rep(0,times=n)
  ans2<-rep(0,times=n)
  ans<-rep(0,times=n)
  G<-rep(0,times=n)
  M<-rep(0,times=n*n)
  N<-rep(0,times=n*n)
  for (i in 1:n){
    G[i]<-rnorm(1)
    for(j in 1:n){
      M[i*n+j]<-rnorm(1)
      N[i*n+j]<-rnorm(1)
      ans1[i]<-ans1[i]+M[i*n+j]*x[j]
      ans2[i]<-ans2[i]+N[i*n+j]*x[j]
    }
  }
  ans<-ans1+ans2+G
  return(ans)
}
x<-c(1:10)
A1(x,10)

```

```{r}
A2<-function(x,n){
  M<-matrix(rnorm(n*n),nrow=n,ncol=n)
  N<-matrix(rnorm(n*n),nrow=n,ncol=n)
  G<-matrix(rnorm(n),nrow=n,ncol=1)
  ans<-crossprod(M,x)+crossprod(N,x)+G
  return(ans)
}
x<-c(1:10)
A2(x,10)
```

```{r}
A1time<-function(){
  #start the clock
  start_time<-Sys.time()
  #loop through 1:10000
  for(i in 1:10000){
    x<-c(1:10)
    A1(x,10)
    #stop the clock
    end_time<-Sys.time()
    t[i]<-end_time-start_time
  }
  plot(1:10000,t,main="Plot for Prob A Function 1",
       xlab="itration n", ylab="time consuming t")
}
A1time()
```

```{r}
A2time<-function(){
  #start the clock
  start_time<-Sys.time()
  #loop through 1:10000
  for(i in 1:10000){
    x<-c(1:10)
    A2(x,10)
    #stop the clock
    end_time<-Sys.time()
    t[i]<-end_time-start_time
}
plot(1:10000,t,main="Plot for Prob A Function 2",
     xlab="itration n", ylab="time consuming t")
}
A2time()
```

## student2 function B
```{python}
import numpy as np
import time
import matplotlib.pyplot as plt

n = 10
def B1(x):
    M=[[0 for i in range(n)] for j in range(n)]
    G=[0 for i in range(n)] 
    ans=[0 for i in range(n)] 
    for i in range(n):
        G[i]=np.random.normal(size = 1)
        ans[i] += G[i]*3
        for j in range(n):
            M[i][j]=np.random.normal(size = 1)
            ans[i] += M[i][j]*M[i][j]*M[i][j]*x[j]
    return ans
print(B2(np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])))
```

```{python}
def B2(x):
    M = np.random.normal(size = (n,n))
    G = np.random.normal(size = (n,1))
    ans = np.zeros((n,1))
    ans = np.add(ans, np.dot(np.power(M, 3), x))
    ans = np.add(ans, G*3)
    return ans
print(B2(np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])))
```

```{python}
def B1time():
    start = time.time()
    ans = []
    for i in range(10000):
        B1(np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]]))
        end = time.time()
        ans.append(end-start)
    plt.plot([i for i in range(10000)], ans)
    plt.show()
B1time()
```

```{python}
def B2time():
    start = time.time()
    ans = []
    for i in range(10000):
        B2(np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]]))
        end = time.time()
        ans.append(end-start)
    plt.plot([i for i in range(10000)], ans)
    plt.show()
B2time()
```

