---
title: "winedata"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
##Use Eulidean distance measurement to calculate distance between two points
distance <- function(p1, p2) {
  ##calculate the two points in matrix
  Matrixdistance <- matrix(NA, nrow=dim(p1)[1], ncol=dim(p2)[1])
  for(i in 1:nrow(p2)) {
    Matrixdistance[,i] <- sqrt(rowSums(t(t(p1)-p2[i,])^2))
  }
  Matrixdistance
}
```


```{r}
##K means algorithm implementation
##mydata<-data stored in matrix
##centers<-centers in kmean
##ntimes<-run algorithm for n times
newkmeans <- function(mydata, centers, ntimes) {
  for(i in 1:ntimes) {
    disttocenter <- distance(mydata, centers)
    clusters <- apply(diststocenter, 1, which.min)
    centers <- apply(mydata, 2, tapply, clusters, mean)
    #Record ith clusters and centers
    finalcluster<- clusters
    finalcenter<- centers
  }
  list(clusters=finalcluster, centers=finalcenter)
}

```

```{r}
#main
wine_scale<-scale(wine[-1])
mdata=as.matrix(wine_scale) #turn into a matrix
centers <- mdata[sample(nrow(mdata), 3),] 
res <- newkmeans(mdata, centers, 10)
res
clusplot(wine_scale, res$cluster)
#plotcluster(wine_scale,res$clusters)
```

